# 需要 docker compose 版本大于 2.20.0
# 按需要导入相关容器配置
# include:
#   - tools/compose/mongodb-compose.yml

include:
  # __base-net 必选
  - tools/compose/__base-net.yml
#  - tools/compose/mysql-compose.yml
#  - tools/compose/redis-compose.yml
  - tools/compose/mongodb-compose.yml