# 需要 docker compose 版本大于 2.20.0
# 按需要导入相关容器配置
# include:
#   - tools/compose/mongodb-compose.yml

include:
  # __base-net 必选
  - tools/compose/__base-net.yml
  - tools/compose/mysql-compose.yml

services:
  # 后端服务
  server:
    build:
      context: .
      # Dockerfile 与 compose.yml 同级，因此不需要额外指定 Dockerfile
      # dockerfile: Dockerfile
    # 容器重启策略，除非手动停止，否则一直重启，选项有：[unless-stopped, always, on-failure, no]
    container_name: "treasure-server"
    restart: unless-stopped
    entrypoint: ["entrypoint.sh"]
    environment:
      # 按需添加
      - TZ=Asia/Shanghai
    volumes:
      # 按需添加
      # - "./logs:/app/logs"
    ports:
      # 按需添加
      # - "8080:8080"
    healthcheck:
      # 健康检查，用于监控容器状态，如果没有则删除健康检查
      test: "curl -f http://localhost:8080"
      # 健康检查间隔时间
      interval: 30s
      # 健康检查超时时间
      timeout: 10s
      # 健康检查重试次数
      retries: 3
      # 健康检查启动时间（等待容器启动多久后开始健康检查）
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        # 最大日志文件大小
        # en: Maximum log file size
        max-size: "100m"
        # 最大日志文件数量
        # en: Maximum log file number
        max-file: "5"
    depends_on:
      # 按需添加
      # - mongodb
    networks:
      # from __base-net.yml
      treasure_net: