include:
  - ./__base-net.yml

services:
  minio-server:
    image: 'minio/minio:RELEASE.2021-04-22T15-44-28Z.hotfix.56647434e'
    container_name: 'minio-server'
    restart: unless-stopped
    command:
      - server |
        --address ':9000' \
        --console-address ':9001' \
        /data
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - TZ=Asia/Shanghai
      - MINIO_ROOT_USER=minio
      - MINIO_ROOT_PASSWORD=minioPasswd
      # https需要指定域名
      #MINIO_SERVER_URL: "https://xxx.com:9000"
      #MINIO_BROWSER_REDIRECT_URL: "https://xxx.com:9001"
      # 关闭文件压缩
      - MINIO_COMPRESS=off
      # 扩展名 .pdf,.doc 为空 所有类型均压缩
      - MINIO_COMPRESS_EXTENSIONS=
      # mime 类型 application/pdf 为空 所有类型均压缩
      - MINIO_COMPRESS_MIME_TYPES=
    volumes:
      - "minio-d:/data"
      - "../conf/minio:/root/.minio/"
    privileged: true
    networks:
      treasure_net:

volumes:
  minio-d: