include:
  - ./__base-net.yml

services:
  mongodb-server:
    # 没有具体要求
    image: "mongo:latest"
    container_name: "mongodb-server"
    restart: unless-stopped
    environment:
      # 数据库用户名
      MONGO_INITDB_ROOT_USERNAME: root
      # 数据库密码
      MONGO_INITDB_ROOT_PASSWORD: rootPassword
    networks:
      # from __base-net.yml
      treasure_net:

  mongo-express:
    image: "mongo-express:latest"
    container_name: "mongo-express"
    ports:
      # 8081 有太多会占用，改成 3066
      # mongo-express 端口
      - "3066:8081"
    environment:
      # mongo-express 用户名
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      # mongo-express 密码
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootPassword
      # mongodb 的数据库端口
      ME_CONFIG_MONGODB_URL: 'mongodb://root:rootPassword@mongodb-server:27017'
      ME_CONFIG_BASICAUTH: false
    networks:
      treasure_net: