include:
  - __base-net.yml

services:
  mysql-server:
    image: "mysql:8.0.36"
    container_name: "mysql-server"
    restart: unless-stopped
    command:
      # 中：使用 mysql_native_password 插件（8 版本中已过时）
      # en: Use mysql_native_password plugin (deprecated in 8.0.36)
      # - --default-authentication-plugin=mysql_native_password
      - --default-authentication-plugin=caching_sha2_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      # 中：启用显式默认值
      # en: Enable explicit defaults
      - --explicit_defaults_for_timestamp=true
    volumes:
      - 'mysql-d:/var/lib/mysql'
      # 用于初始化数据库
      # 需要修改
      # - '../sql:/docker-entrypoint-initdb.d/'
      # MySQL 配置文件
      - '../conf/mysql/custom.cnf:/etc/mysql/my.cnf'
    environment:
      # 中：时区
      # en: Time zone
      - TZ=Asia/Shanghai
      # 中：数据库密码
      # en: Database root password
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      # 中：数据库名称
      # en: Database name
      - MYSQL_DATABASE=treasure
      # 中：数据库用户名
      # en: Database username
      - MYSQL_USER=treasure
      # 中：数据库密码
      # en: Database password
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    ports:
      - "3306:3306"
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        # 最大日志文件大小
        # en: Maximum log file size
        max-size: "1G"
        # 最大日志文件数量
        # en: Maximum log file number
        max-file: "5"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      # from __base-net.yml
      treasure_net:

volumes:
  mysql-d:

secrets:
  - db_root_password:
      file: ./db_root_password.txt
  - db_password:
      file: ./db_password.txt