include:
  - __base-net.yml

services:
  mysql-server:
    image: "mysql:8.0.36"
    container_name: "mysql-server"
    restart: unless-stopped
    command:
      # 使用 mysql_native_password 插件（8 版本中已过时）
      # - --default-authentication-plugin=mysql_native_password
      - --default-authentication-plugin=caching_sha2_password
      - --character-set-server=utf8
      - --collation-server=utf8_general_ci
      # 启用显式默认值
      - --explicit_defaults_for_timestamp=true
    volumes:
      - 'mysql-d:/var/lib/mysql'
      # 用于初始化数据库
      # 需要修改
      # - '../sql:/docker-entrypoint-initdb.d/'
      # MySQL 配置文件
#      - '../conf/mysql/custom.cnf:/etc/mysql/my.cnf'
    environment:
      # 时区
      - TZ=Asia/Shanghai
      # 数据库密码
      - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db_root_password
      # 数据库名称
      - MYSQL_DATABASE=treasure
      # 数据库用户名
      - MYSQL_USER=treasure
      # 数据库密码
      - MYSQL_PASSWORD_FILE=/run/secrets/db_password
    secrets:
      - db_root_password
      - db_password
    ports:
      - "3306:3306"
    tty: true
    stdin_open: true
    logging:
      driver: "json-file"
      options:
        # 最大日志文件大小
        max-size: "1G"
        # 最大日志文件数量
        max-file: "5"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      # from __base-net.yml
      treasure_net:

volumes:
  mysql-d:

secrets:
  db_root_password:
      file: ../secrets/db_root_password.txt
  db_password:
      file: ../secrets/db_password.txt