include:
  - tools/compose/__base-net.yml

services:
  mysql-server:
    image: "mysql:8.0.36"
    container_name: "mysql-server"
    restart: unless-stopped
    volumes:
      - 'mysql-d:/var/lib/mysql'
      # 用于初始化数据库
      # 需要修改
      # - '../sql:/docker-entrypoint-initdb.d/'
    environment:
      - MYSQL_ROOT_PASSWORD=root123
      - TZ=Asia/Shanghai
    ports:
      - "3306:3306"
    tty: true
    stdin_open: true
    networks:
      treasure_net:

volumes:
  mysql-d:
